const DeliverabilitySection = () => {
  const features = [
    {
      title: "Proactive Blocklist Tracking",
      description: "Be the first to know if your domain is added to a DNSBL such as those offered by Spamhaus with removal requests generated by Resend.",
    },
    {
      title: "Faster Time to Inbox",
      description: "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.",
    },
    {
      title: "Build Confidence with BIMI",
      description: "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media.",
    },
    {
      title: "Managed Dedicated IPs",
      description: "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
    },
    {
      title: "Dynamic Suppression List",
      description: "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.",
    },
    {
      title: "IP and Domain Monitoring",
      description: "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
    },
    {
      title: "Verify DNS Records",
      description: "Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.",
    },
    {
      title: "Battle-Tested Infrastructure",
      description: "Rely on a platform of reputable IP's used by trustworthy senders with distributed workloads across different IP pools.",
    },
    {
      title: "Prevent Spoofing with DMARC",
      description: "Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email.",
    },
  ];

  return (
    <section className="py-24 md:py-32 bg-surface">
      <div className="container">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-carbon tracking-tight mb-4 uppercase">
            Reach humans, not spam folders
          </h2>
          <p className="text-muted-foreground text-lg">
            Enterprise-grade infrastructure that ensures your emails reach the inbox.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="p-6 bg-background border border-zinc-200 rounded-lg shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="w-8 h-8 rounded bg-[#00A3FF]/10 flex items-center justify-center mb-4">
                <div className="w-3 h-3 rounded-full bg-[#00A3FF]" />
              </div>
              <h3 className="text-base font-bold text-carbon mb-2">
                {feature.title}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default DeliverabilitySection;
